apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kubeconfigSecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  kubeconfig: |-
    apiVersion: v1
    kind: Config
    clusters:
    - name: my-cluster
      cluster:
        certificate-authority-data: {{ index .Data "ca.crt" | b64enc }}
        server: {{ .Values.kubernetesAPIHost }}
    contexts:
    - name: my-context
      context:
        cluster: my-cluster
        user: my-user
    current-context: my-context
    users:
    - name: my-user
      user:
        token: {{ index .Data "token" | b64enc }}
