apiVersion: v1
kind: ConfigMap
metadata:
  name: generate-kubeconfig-script
data:
  generate_kubeconfig.sh: |
    #!/bin/sh
    
    # Variables
    CA_CRT="/root/.kube/ca.crt"
    NAMESPACE="/root/.kube/namespace"
    TOKEN="/root/.kube/token"
    OUTPUT_FILE="/app/kubeconfig"
    
    # Création du contenu du kubeconfig
    cat <<EOF > "\${OUTPUT_FILE}"
    apiVersion: v1
    kind: Config
    clusters:
    - name: my-cluster
      cluster:
        certificate-authority: \${CA_CRT}
        server: https://kubernetes.docker.internal:6443
    contexts:
    - name: my-context
      context:
        cluster: my-cluster
        namespace: \$(cat \${NAMESPACE})
        user: restricted-sa
    current-context: my-context
    users:
    - name: restricted-sa
      user:
        token: \$(cat \${TOKEN})
    EOF
    
    # Affichage du contenu généré (facultatif)
    echo "Contenu généré pour \${OUTPUT_FILE}:"
    cat "\${OUTPUT_FILE}"
    
    # Assurez-vous que le fichier kubeconfig a les bonnes permissions (facultatif)
    chmod 600 "\${OUTPUT_FILE}"
