{{- if .Values.secretSyncController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-sync-controller
  namespace: {{ .Values.secretSyncController.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-sync-controller
  template:
    metadata:
      labels:
        app: secret-sync-controller
    spec:
      serviceAccountName: {{ .Values.secretSyncController.serviceAccount.name }}
      containers:
        - name: secret-sync-controller
          image: "{{ .Values.secretSyncController.image.repository }}:{{ .Values.secretSyncController.image.tag }}"
          imagePullPolicy: {{ .Values.secretSyncController.image.pullPolicy }}
          env:
            - name: NAMESPACE
              value: {{ .Values.secretSyncController.namespace }}
{{- end }}
