apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kubeconfigSecret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: restricted-sa
type: kubernetes.io/service-account-token
data:
  token: {{ .Values.serviceAccount.token }}


