{{- if .Values.secretSyncController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secretSyncController.serviceAccount.name }}
  namespace: {{ .Values.secretSyncController.namespace }}
{{- end }}
